[editor]
auto-pairs = true
auto-save = true
bufferline = "multiple"
color-modes = true
completion-trigger-len = 1
cursorline = true
idle-timeout = 0
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[editor.lsp]
auto-signature-help = false
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator", "file-encoding"]
center = ["version-control", "spacer", "diagnostics"]
right = ["selections", "register", "position", "position-percentage"]

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
tabpad = " "
