[editor]
auto-pairs = false
auto-save = true
bufferline = "multiple"
completion-trigger-len = 1
cursorline = true
idle-timeout = 0
indent-guides.render = true
line-number = "relative"
whitespace.render = "all"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator", "file-encoding"]
center = ["version-control", "spacer", "diagnostics"]
right = ["selections", "position", "position-percentage"]

[editor.soft-wrap]
enable = true