[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Beam"
thickness = 0.2

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[general]
live_config_reload = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
decorations = "None"
startup_mode = "Fullscreen"
