#!/bin/zsh
alias rm="rm -v"
if test $UNAME = "Darwin" ;
then
	alias ls="ls -GFT" ;
	alias cp="cp -H" ;
elif test $UNAME = "Linux" ;
then
	alias ls="ls --color=auto" ;
	alias cp="cp --dereference" ;
else
	alias ls="ls --color=auto" ;
	alias cp="cp --dereference" ;
fi
alias ll="ls -lh"
alias la="ll -a"
alias less=$PAGER
alias zless=$PAGER
alias vless=/opt/local/share/vim/vim73/macros/less.sh
alias grep="grep --color=auto"
alias bc="bc -ql"
alias vimdiff="vim -d"
alias moc="mocp"

# Alias for Git
alias ga="git add"
alias gc="git commit"
alias gca="git commit -a"
alias gdf="git df"
alias gf="git fetch"
alias gi="git ignore"
alias gph="git push"
alias gpl="git pull"
alias grm="git rm"
alias gss="git status"

# To extract files
function extract() {
	if test -f $1
	then
		case $1 in
			*.tar.bz2)
				tar xvjf $1 ;;
			*.tbz2)
				tar xvjf $1 ;;
			*.tar.gz)
				tar xvzf $1 ;;
			*.tgz)
				tar xvzf $1 ;;
			*.bz2)
				bunzip2 $1 ;;
			*.rar)
				rar x $1 ;;
			*.gz)
				gunzip $1 ;;
			*.zip)
				unzip $1 ;;
			*.Z)
				uncompress $1 ;;
			*)
				echo "'$1' cannot be extracted with 'extract'" ;;
		esac
	else
		echo "'$1' is not a valid file for extraction"
	fi
}
alias extract="extract"
