#!/bin/zsh
alias rm="rm -v"
if [ $UNAME = "Darwin" ]
then
	alias ls="ls -GFT" ;
	alias cp="cp -H" ;
elif [ $UNAME = "Linux" ]
then
	alias ls="ls -F --color=auto" ;
	alias cp="cp --dereference" ;
else
	alias ls="ls -F --color=auto" ;
	alias cp="cp --dereference" ;
fi
alias ll="ls -lh"
alias la="ls -ha"
alias lla="ll -a"
alias less=$PAGER
alias zless=$PAGER
alias vless=/opt/local/share/vim/vim73/macros/less.sh
alias grep="grep --color=auto"
alias bc="bc -ql"
alias moc="mocp"
if [ "$( command -v tree )" = '' ] 
then
	alias tree="find . | sed 's/[^/]*\\//│   /g;s/│ *\\([^│ ]\\)/├── \\1/'"
fi

# Alias for Git
alias ga="git add"
alias gc="git commit"
alias gca="git commit -a"
alias gdf="git df"
alias gf="git fetch"
alias gi="git ignore"
alias gph="git push"
alias gpl="git pull"
alias grm="git rm"
alias gss="git status"
alias gls="git ls"

# Alias for Tmux
alias tns="tmux new-session -s"
alias tas="tmux attach -t"
alias tls="tmux list-sessions"

function concat-path() {
	DIRNAME="$1"
	BASENAME="$2"
	EXTNAME="$3"
	if [ $DIRNAME = "." ]
	then
		if [ -z $EXTNAME ]
		then
			echo $BASENAME
		else
			echo $BASENAME"."$EXTNAME
		fi
	else
		if [ -z $EXTNAME ]
		then
			echo $DIRNAME"/"$BASENAME
		else
			echo $DIRNAME"/"$BASENAME"."$EXTNAME
		fi
	fi
}

function insert-date() {
	if [ -d $1 ]
	then
		DIRNAME=`dirname $1`
		FILENAME=`basename $1`
		DATE="`date +%Y-%m-%d_%H-%M-%S`"
		concat-path "$DIRNAME" "$FILENAME" "$DATE"
	else
		DIRNAME=`dirname $1`
		FILENAME=`basename $1`
		BASE="${FILENAME%.[^.]*}"
		EXT="${FILENAME:${#BASE}+1}"
		OUTBASE="$BASE"."`date +%Y-%m-%d_%H-%M-%S`"
		concat-path "$DIRNAME" "$OUTBASE" "$EXT"
	fi
	unset DIRNAME FILENAME BASE EXT OUTBASE
}

function remove-date() {
	DIRNAME=`dirname $1`
	FILENAME=`basename $1`
	BASE="${FILENAME%.[^.]*}"
	EXT="${FILENAME:${#BASE}+1}"
	OUTBASE=`echo $BASE | sed 's/\.[0-9-]\{10\}_[0-9-]\{8\}$//g'`
	concat-path "$DIRNAME" "$OUTBASE" "$EXT"
	unset DIRNAME FILENAME BASE EXT OUTBASE
}

function bak() {
	if [ -d $1 ]
	then
		cp -R "$1" `insert-date "$1"`
	else
		cp "$1" `insert-date "$1"`
	fi
}
alias bak="bak"
alias bd='. bd -s'
alias xmlformat="xmllint --format"

# Dictionaries
alias dicte="dict -d gcide"
alias dictef="dict -d fd-eng-fra"
alias dictfe="dict -d fd-fra-eng"
