#!/bin/zsh

# zsh-autosuggestions
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'
# CTRL+ENTER to accept and execute the command
bindkey '^' autosuggest-execute
