colorscheme gruvbox

# remove clippy from popups
set-option global ui_options ncurses_assistant=off

# add line numbers
add-highlighter global/ number-lines

hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
        hook -once -always window InsertCompletionHide .* %{
            map window insert <tab> <tab>
            map window insert <s-tab> <s-tab>
        }
    }
}

define-command -hidden -params 1 increment-number %{
    evaluate-commands %sh{
        printf 'exec h"_/\d<ret><a-i>na%s1<esc>|bc<ret>\n' "$1"
    }
}
map global normal <c-a> ':increment-number +<ret>'
map global normal <c-x> ':increment-number -<ret>'
