version: '3.2'
services:
    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_DB: 'freshrss'
            POSTGRES_USER: 'freshrss'
            POSTGRES_PASSWORD: 'freshrss'

    freshrss:
        image: freshrss/freshrss:1.19.1
        restart: always
        links:
            - postgres
        volumes:
            - type: 'bind'
              source: './freshrss-data'
              target: '/var/www/FreshRSS/data'
            - type: 'bind'
              source: './freshrss-extensions'
              target: '/var/www/FreshRSS/extensions'
        ports:
            - "127.0.0.1:8889:80"
        environment:
            - CRON_MIN=13,43
