version: '2'
services:
    transmission:
        image: linuxserver/transmission:26
        restart: always
        environment:
            PGID: '1000'
            PUID: '1000'
            TZ: 'America/Detroit'
        volumes:
            - "./config:/config"
            - "./downloads:/downloads"
            - "./watch:/watch"
        ports:
            - "127.0.0.1:9091:9091"
            - "51413:51413"
            - "51413:51413/udp"
