#!/bin/zsh

# Load colors is necessary to define "fg" and "bg"
autoload -U colors
colors

# Define the prompt
# %B/%b is for play/stop bold text
# %n display the username
# %m display the hostname
# %~ display the current directory (factorized with ~for home if possible)
# %f reset the colors to the default
# %D display the date (see strftime documentation)
# %* display the hour
# %_ display the current loop ("for" for example)
# %N display the current script
# %i display the current line
ZSH_THEME_GIT_PROMPT_PREFIX="$FG[255]<$FG[238]git:$FG[070]"
ZSH_THEME_GIT_PROMPT_CLEAN="-%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY="$FG[202]+%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="$FG[255]>%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_AHEAD="$FG[202]*%{$reset_color%}"

PROMPT='$BG[232]$FG[244]--- $BG[233]%n@%m [%D{%d/%m/%y}-%*]$BG[232] ---%{$reset_color%}
$FG[105]%~/\
$FG[255]%(!.#.>)%{$reset_color%} '
PROMPT2='%{$fg[yellow]%}%_> %{$reset_color%}'

# right prompt
RPROMPT='$(git_prompt_info)$(git_prompt_ahead)'
RPROMPT2='%{$fg[yellow]%}\ %{$reset_color%}'
