[signing]
sign-all = true
backend = "gpg"
key = "7D7767B4"

[ui]
default-command = ["log", "--reversed"]
diff-editor = "meld"

[user]
name = "Jean SIMARD"
email = "woshilapin@tuziwo.info"

[merge-tools.meld]
program = "guix"
edit-args = ["shell", "meld", "--", "meld", "--newtab", "$left", "$right"]
