[signing]
sign-all = true
backend = "gpg"
key = "7D7767B4"

[ui]
default-command = ["log", "--reversed"]
diff-editor = ":builtin"

[user]
name = "Jean SIMARD"
email = "woshilapin@tuziwo.info"

[template-aliases]
signoff_enabled = 'false'

[templates]
draft_commit_description = '''
concat(
  description,
  "\n",
  if(
    signoff_enabled && !description.contains("Signed-off-by: " ++ author.name() ++ " <" ++ author.email() ++ ">"),
    "\nSigned-off-by: " ++ author.name() ++ " <" ++ author.email() ++ ">",
  ),
  "\n",
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.summary()),
  ),
)
'''
