#!/bin/zsh
# PATH initialisations
UNAME=`uname`
if [ $UNAME = "Linux" ]
then
	PATH=$PATH:/usr/local/sbin:/usr/sbin:/sbin
elif [ $UNAME = "Darwin" ]
then
	PATH=/opt/local/bin:/opt/local/sbin:$PATH
	LIBRARY_PATH=/opt/local/lib:$LIBRARY_PATH
fi
PATH=~/.zsh/scripts:$PATH
PATH=/opt/woshilapin/bin:$PATH
export PATH
export LIBRARY_PATH
# TRASH initialisations
if [ $UNAME = "Linux" ]
then
	TRASH_DIR=~/.trash ;
elif [ $UNAME = "Darwin" ]
then
	TRASH_DIR=~/.Trash ;
fi
export UNAME
export TRASH_DIR
export LANG=fr_FR.UTF-8
export LANGUAGE=fr_FR:fr:en_US:en_GB:en
unset LC_ALL
if [ $UNAME = 'Darwin' ]
then
	export EDITOR=/opt/local/bin/vim
else
	export EDITOR=/usr/bin/vim
fi
export PAGER=/usr/bin/less
declare -x TEXINPUTS=.:$HOME/.texmf:
# For java
JAVA_HOME_LIST=/usr/lib/jvm/java-6-sun:/usr/lib/jvm/default-java
# Select the first available directory for JAVA_HOME
if [ $UNAME = 'Linux' ]
then
	for dir in `echo $JAVA_HOME_LIST | sed 's/:/ /g'`                                                                                                                   
	do
		if test -d $dir
		then
			export JAVA_HOME=$dir
			break
		fi
	done
fi
PULSE_LATENCY_MSEC=60

export MPD_HOST="${HOME}/.config/mpd/mpd.socket"
export NVM_DIR="$HOME/.dot/nvm"
[ -s "$NVM_DIR/nvm.sh"  ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
export PATH="${HOME}/.cargo/bin:${PATH}"

# Disable automatic titles (useful for correct naming of tmux tabs with tmuxinator)
export DISABLE_AUTO_TITLE=true
