#!/bin/zsh
# PATH initialisations
UNAME=`uname`
if [ ${UNAME} = "Linux" ]
then
	export PATH=${PATH}:/usr/local/sbin:/usr/sbin:/sbin
elif [ ${UNAME} = "Darwin" ]
then
	export PATH=/opt/local/bin:/opt/local/sbin:${PATH}
	export LIBRARY_PATH=/opt/local/lib:${LIBRARY_PATH}
fi
if [[ ! "${PATH}" =~ '.zsh/scripts' ]]
then
	export PATH=~/.zsh/scripts:${PATH}
fi
if [[ ! "${PATH}" =~ '/opt/woshilapin/bin' ]]
then
	export PATH=/opt/woshilapin/bin:${PATH}
fi
# TRASH initialisations
if [ ${UNAME} = "Linux" ]
then
	TRASH_DIR=~/.trash ;
elif [ ${UNAME} = "Darwin" ]
then
	TRASH_DIR=~/.Trash ;
fi
export UNAME
export TRASH_DIR
export LANG=fr_FR.UTF-8
export LANGUAGE=fr_FR:fr:en_US:en_GB:en
unset LC_ALL
export EDITOR=vim
export PAGER=less
declare -x TEXINPUTS=.:${HOME}/.texmf:
# For java
JAVA_HOME_LIST=/usr/lib/jvm/java-6-sun:/usr/lib/jvm/default-java
MAVEN_OPTS="--active-profiles SECURITY --define http.proxyHost=proxy3.us.dominos.com --define http.proxyPort=8080 --define https.proxyHost=proxy3.us.dominos.com --define https.proxyPort=8080 --define http.nonProxyHosts=localhost\|*.us.dominos.com\|*.dominos.com --define java.awt.headless=true"
# Select the first available directory for JAVA_HOME
if [ ${UNAME} = 'Linux' ]
then
	for dir in `echo ${JAVA_HOME_LIST} | sed 's/:/ /g'`                                                                                                                   
	do
		if test -d ${dir}
		then
			export JAVA_HOME=${dir}
			break
		fi
	done
elif [ ${UNAME} = 'Darwin' ]
then
	# Use '/usr/libexec/java_home -V' to determine available versions
	# Edit file '.java_version' to change your current version
	# If version is '1.8.0_144', you can put only '1.8.0' or '1.8'
	export JAVA_HOME=$( /usr/libexec/java_home -v $( cat ~/.java_version ) )
fi
PULSE_LATENCY_MSEC=60

export MPD_HOST="${HOME}/.config/mpd/mpd.socket"
export NVM_DIR="${HOME}/.dot/nvm"
[ -s "${NVM_DIR}/nvm.sh"  ] && \. "${NVM_DIR}/nvm.sh"  # This loads nvm
if [[ ! "${PATH}" =~ '.cargo/bin' ]]
then
	export PATH="${HOME}/.cargo/bin:${PATH}"
fi

# Disable automatic titles (useful for correct naming of tmux tabs with tmuxinator)
export DISABLE_AUTO_TITLE=true

# Base16
BASE16_SHELL="/home/woshilapin/.local/share/base16-manager/chriskempson/base16-shell"
[ -n "$PS1" ] && \
	[ -s "$BASE16_SHELL/profile_helper.sh" ] && \
	eval "$( "$BASE16_SHELL/profile_helper.sh" )"

# SSH Agent (will export the necessary environment variables for 'ssh-add')
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-pid
fi
if [[ ! "$SSH_AUTH_SOCK" ]]
then
    eval "$(<~/.ssh-agent-pid)" > /dev/null
fi

# Pyenv
if [[ ! "${PYENV_ROOT}" ]]
then
	export PYENV_ROOT="${HOME}/.pyenv"
fi
if [[ ! "${PATH}" =~ "${PYENV_ROOT}/bin" ]]
then
	export PATH="${PYENV_ROOT}/bin:${PATH}"
fi
if command -v pyenv 1>/dev/null 2>&1
then
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
fi

export FZF_DEFAULT_OPTS="--reverse --border --inline-info --tabstop=4 --color=dark --preview='test -e {} && echo -n \"\033[1;34m\" && file --brief {} && echo -n \"\033[0m\" && head -$LINES {}'"
