configuration-data:
    image: spiroid/cozy-conf

couchdb-data:
    image: spiroid/cozy-couchdb-data

couchdb:
    image: spiroid/cozy-couchdb
    restart: always
    volumes_from:
        - couchdb-data
        - configuration-data

dataindexer:
    image: spiroid/cozy-data-indexer
    hostname: dataindexer
    restart: always
    volumes_from:
        - configuration-data

controller:
    image: spiroid/cozy-controller
    restart: always
    links:
        - couchdb
        - dataindexer
    volumes_from:
        - configuration-data
        - dataindexer
    ports:
        - "127.0.0.1:9002:9002"
        - "127.0.0.1:9104:9104"
